hash-format = "sha256"

[[files]]
file = "config/MouseTweaks.cfg"
hash = "4069ce1a439d8c37453c1b1e9f2037e0942674c7e48723a39b37eab245792ad4"

[[files]]
file = "config/alltheheads-common.toml"
hash = "b5877430b97e89a55459c391e90ae66d293dfb9e996704fdec5d9368282d013c"

[[files]]
file = "config/armorposer.toml"
hash = "51b2e2ef12025eeeb4b288857504b886d884f32beb435e5de80101f0114a6efb"

[[files]]
file = "config/chat_heads.json5"
hash = "2e33e5590888ad9c37d35ef6ef29d50e8ab7430ee7fd572a69b3583428abebf9"

[[files]]
file = "config/collective.json5"
hash = "b6243b955bf123f86c947510d9f8f3a4b5f7b8fe3775d834f458d60a3223847f"

[[files]]
file = "config/cubes-without-borders.json"
hash = "f248bc2019d956312c0c18037b84e764947dd200c00a96f45a807624d233010d"

[[files]]
file = "config/enchdesc.json"
hash = "7116b95a9b6797af8db84e410a2ca2fdf6f813461e37cd04bff5af933f31567b"

[[files]]
file = "config/entity_model_features.json"
hash = "a409f75f21a3189f06c4edf5bf6b613c3c6275147c8b51ae1e1c46e8e8cdb8ef"

[[files]]
file = "config/entity_texture_features.json"
hash = "0554c0e7816266477c65c18d2ada9fdddf1c6750787efd329056223ca4a073b2"

[[files]]
file = "config/etf_warnings.json"
hash = "a5ba22e63061c1fb67f0f895f17681351eaeccc225faef966c29ee630593275e"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "bbf2ec396ac2cd620d7e0b11f69a63a0e4a5ccc64069436f0a8b5697bf5a5a29"

[[files]]
file = "config/forgeconfigapiport.toml"
hash = "40dbe5b348f89b8ded62bcdfe32807ffc3e78fa8e0f81607a739580019fe5450"

[[files]]
file = "config/freecam.json5"
hash = "442d3c73c8d0c64a2445ef0c31b618db0034a2f452bf15751ec337287f34ef0c"

[[files]]
file = "config/horsestatsmod.json5"
hash = "0f869508d8e50a5e4ffb9227e6cd8d9bf20a52db6adeecfd6e15716986f4ee9e"

[[files]]
file = "config/inventorysorter.json"
hash = "290ec925140cc45ff6e4172395badf177b1d3dca27dc33e22a299a31cfdb53f3"

[[files]]
file = "config/journeymap-server.json"
hash = "2b77ff82093eb3698b79b2b953806855d1880d414544a8158f41b028d8e293ca"

[[files]]
file = "config/justmobheads.json5"
hash = "c5bcdc35b6c4fb7e5a96d552c10c13302c95956b3d6b038817cb97cd26f42801"

[[files]]
file = "config/justmobheads/headchances.txt"
hash = "287768970910d388c79720409c0ae0096cf5c22d932e0e27c1f5ce1e58c15f84"

[[files]]
file = "config/justplayerheads.json5"
hash = "f1f888cb5f0da0d8c6dd2aaa866e15f4ceef00528d3602e24a2b7fef7d4b4dd0"

[[files]]
file = "config/justzoom/config.txt"
hash = "d0dcbc7c9c28a398ad2b81c1f6779f34beffbf45560c8c02c063077ab32ded45"

[[files]]
file = "config/lambdynlights.toml"
hash = "fdd6958ff17541c8d1c891bd1602088bb6888f41229e966387a07311f32ec6d9"

[[files]]
file = "config/litematica.json"
hash = "6e39cafdb95f1b937cd31de3eae579e6226f498c0c2e9aa4cb19cd62b9c0dda5"

[[files]]
file = "config/litematica/litematica_New World.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_New World_dim_minecraft_overworld.json"
hash = "adcadb841e38244e0121845e5c11366cb7fca48d1e6518db75eb8369eb9cc582"

[[files]]
file = "config/locator-heads.json"
hash = "dd07c3b60c50b02cab3287df914f7127e4edd1decbc2d16ebb65fe7a9e512c6c"

[[files]]
file = "config/lootr.json"
hash = "1c0fbe0965bdfb1271b7be90e86bc4fbd9114bb768fc0a4995da0f3621531bfc"

[[files]]
file = "config/malilib.json"
hash = "33d9f347c14aeaa05b845cb56a9704e979f0aa54c29165827f2980a688f344f6"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/polymer/auto-host.json"
hash = "26ab57411745916fa6bf5f54b0df43dda04e3b6d379a5b3fdec94ad6d56f2382"

[[files]]
file = "config/polymer/client.json"
hash = "d8a4e36c8c4df8c5612aa9485d6a2e7a43cb2aa7f1584a52bb6373d6c94037c4"

[[files]]
file = "config/polymer/common.json"
hash = "310dee45deffb1f13169492bf25cee00503e91403daa8cffa653939feb76cc03"

[[files]]
file = "config/polymer/resource-pack.json"
hash = "7a4243c13c9606c7cc046ae66f36979b87bd7924baef657dbb577cb4375c2e95"

[[files]]
file = "config/polymer/server.json"
hash = "eaec27618070f4daf636a5e8457c978e1d9afffa22fba907eca29cdd700a94d2"

[[files]]
file = "config/polymer/sound-patch.json"
hash = "f815116c7a6a7ba28de432cf2be7fdbf49e2e1adb5436438d347d391ee3b5c74"

[[files]]
file = "config/shulkerdropstwo.json5"
hash = "c51a8d28d4e34f2fa558cb57aef6e8c023a501c11e2eadf7e4aafdfa8b1032d0"

[[files]]
file = "config/simple_harvesting.json"
hash = "59b04156dcbdfb7c4ebf99c3467a67f6c978af45e99d93ea4e515f36faa0b52f"

[[files]]
file = "config/skinlayers.json"
hash = "980b9889cf6a14d2df8cd14c269b307b48743afeadaa38d14395f1c8d9e874db"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "bca02fec42be5a3794055eee644bd895e21c9a66004343ed60965f45338ef472"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "d3482af3895ad31a3b9c59b26807eb9944ede706b3d314668ad83c94d61bd195"

[[files]]
file = "config/trade_cycling/trade_cycling.properties"
hash = "5610bec5a681bd00da2bd273f7eadc1cc03864b1059461860b8ece325db9341d"

[[files]]
file = "config/universal-graves/config.json"
hash = "e5de99ef8cf0b47ade7d9248385778d33bdecae381fc4ee246d2c54749c7d81a"

[[files]]
file = "config/universal-graves/example_models/corpse_player.json"
hash = "f1f86bd740c9bde120cca8769e900005cf46f67cfb076b65b50c339f47deb69e"

[[files]]
file = "config/universal-graves/example_models/corpse_zombie.json"
hash = "dc1ee62c77ef7831f52c1c9a44c5dff3e5ccaa4094d43438e9fdbe1f41a06a17"

[[files]]
file = "config/universal-graves/example_models/default.json"
hash = "c0f6c5e52fcfe066b1b300e9c4c738feb87dc1397ce45e58b99b63cb25e07167"

[[files]]
file = "config/universal-graves/example_models/ender.json"
hash = "87be637b2b08c7f97550362d66f1682ce475c4c29a470f96a44cdf86f6dc6c0e"

[[files]]
file = "config/universal-graves/example_models/player_head.json"
hash = "c0f6c5e52fcfe066b1b300e9c4c738feb87dc1397ce45e58b99b63cb25e07167"

[[files]]
file = "config/universal-graves/example_models/soul.json"
hash = "bd3c7cba512978e4d0f5632aed773b47d93e80e9243656fc092d6cc56ddc53e1"

[[files]]
file = "config/visuality.json"
hash = "1561b99ae57ede995dfb64a91ac5b53dd877f57e4a8f1859526da84511bcec07"

[[files]]
file = "config/voicechat/category-volumes.properties"
hash = "94c1c4f70e5b995fbd71e86d4fa646030437fecae0685875b560a55fbd0d0e56"

[[files]]
file = "config/voicechat/player-volumes.properties"
hash = "0332261861a5ace96f503e85b0d48a8df74ea6c2f3545cd229543a6afb55ad96"

[[files]]
file = "config/voicechat/translations.properties"
hash = "693643b1d393cbb3ea7f062afc4474fcd66e4036c4f8d7c056434979cbf512d1"

[[files]]
file = "config/voicechat/username-cache.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "03a06f4edb8f22aba820574850c05c803f6b153d040f28a5e9a857b433875a2a"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "4d0be0e743b48609d932f435f0dd496041c6eb0356691ef5c22b786d137987a3"

[[files]]
file = "mods/ArmorPoser-fabric-1.21.10-12.2.0.jar"
hash = "0abad1aa1b94f12d2b8c0a8138f510fc783a87a4d8b9de0d5283386cb22af9fc"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "918fff55bddc212fcd9300643db1db2f87eded6e0f8766b1e1f19ed4d14588dc"
metafile = true

[[files]]
file = "mods/betterstats.pw.toml"
hash = "c6b8af91f201644f75711d5605b15203c9bbfc986df00e1b17176628c1914a4d"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2bfc0ee79cc78491a0d15bcf658242873ce38dc9236bbcfa1ae0ba365e89807f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "de8e021e0beacab839ca3bd4dfdb30fa5f3cfd1e71be722ccf56373908b41a7f"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "20b037ab061b2e1a54d4c4bb711700dbe081fa75049fa5cf3e236b87efd9418d"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a826fbce1a20169613e387719b40a05e95a0ca8ede805b82fa686533a0550713"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "5efa86151272ba0a9b018250831f7bea366ab8f9ab7dbabf7f1e839dd3195102"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9e4b2cf1dca69ba51fabff222342548b611239f13e7d0a34166c1a873738bd2b"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "c1275abed053512d821985a3f881f6cba8c8d1095976d1da2cb5de5a2b89ed2f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "189134fe48404ea4f716f6ee705d5af668a493264c1af07b02ce18113b346de9"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "65255c87bd3bf84de532144811557741121766878c8366c929df9261c0fd1cb0"
metafile = true

[[files]]
file = "mods/free-cam.pw.toml"
hash = "2de90753ffd44eaaa3b765bcdb1253d7100b2f40c6bad24bbf50881d082650e6"
metafile = true

[[files]]
file = "mods/horse-statistics.pw.toml"
hash = "2bfc5240cd51d779f1cb6fcc4bd2de152f1b23f7aa82ff715112f81ef3f86eca"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "da7afc337a00ba609eaa38b8e917e12fae668de4974fb36cf6f63ae6ddcaecbd"
metafile = true

[[files]]
file = "mods/journeymap-fabric-1.21.10-6.0.0-beta.53.jar"
hash = "a6a819e8bf9115267cc13f23d777b9534c67fe1efbe53d5d819f32a9d7737438"

[[files]]
file = "mods/just-mob-heads.pw.toml"
hash = "289f86776818c755bca97890177c8de4a9141af8f44a2391fcee389f736fc620"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "11bceee034ad74f1a4562dbdba2c7c0aed122ed58ed8de02b2239dff547d6fdd"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "16ed270a60d4751af2745ebece1f50c8488799f86f1623dfbc6a155d8ce21de3"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "7e57ad6b081aff8be050e3e72938cda571345862c3b587c6802d68c5c2095e45"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8036cf2bc316b514ce60085189ab2324ad2339f465b0cdf001581f89c18a8cbd"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "510364a689ac02def5b5f50f511fc2e972b764b341564d96d51ade4fefcfc009"
metafile = true

[[files]]
file = "mods/locator-heads-1.3.1.jar"
hash = "f9f782883774c3d56f85439de440c03c91991fa8dd4852983bbd7500f73ef7cc"

[[files]]
file = "mods/lootr-fabric.pw.toml"
hash = "5617b01a4019b3599defb317367094051d003f00953b01d364a2866c36597af5"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "0fb690b118e6febdc98689def46c4feb39b9c935a544684f87dde46e29758bc9"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "571d53be7a248e0961bf769252695b996e14c5daa70a298c52877844ebc8b20f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9a5062df61e09bf79936d0987a252aac26506b51d7c02107e4ca386c0c5a196c"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "46d9e7e8ab17717bff19ce7fd4f9ee08838b2b3e5ffb30f9218407e8ad23871d"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "8840a2cce53e7e051879a9561fbfd43bb5a40d85cb73edd27646ec8e280b0f0a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "ec9ec7d0c5cd7c0183711c8281d1aaaa0043ca99972ef0c4afd931d3d4bb796c"
metafile = true

[[files]]
file = "mods/rounds-invisible-frames.pw.toml"
hash = "943f8a5db0799a89fba3b468888ca8993639f221c096d23471c4878bba34693c"
metafile = true

[[files]]
file = "mods/shulker-drops-two.pw.toml"
hash = "44d39627583a61bc3295e9b6b8b2302b78a07ae0f6477121e515ed4e34e1a4f8"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip-fabric-5.2.11+1.21.9.jar"
hash = "d2fe1ec48694b023215257c1cee859c0ead4d80cc02b5871823961c041786af7"

[[files]]
file = "mods/simple-harvesting.pw.toml"
hash = "6e06b9206c9c88c64e3133a5d1d08482007032ad68621766f5d60189b6efb6b4"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0dddfa777706acc5ed3175738f377e95c07bf2e88d549138d5b0d2518c2f88a2"
metafile = true

[[files]]
file = "mods/skin-layers-3d.pw.toml"
hash = "fb012b2d544560ae82b7bfa09f2716aaafc3890ba7fc0f5183f23b723292d2a8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "24aa12652da15e0e2d788a4cc2144ef908d6b4a792b644becd64ca3e1bfe4fe7"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "27dc7fefde6ef779c53c2c517ab6992373c2266ca812661d65facf72e6bb31d0"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c5fdf842ac50d5992853c9c6f073d876d358913b161498eb2f52b1de58d2a390"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "9e5c8eed53af26e1eaa584599174e0ace1609a1601332b9a8ff635c2fcec8229"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "5c5cdc08ec933a04c41d4de4b779773a9b5dc56f7d6ab8b6e677d5e26abc2475"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "f49c6cc93bf7527571e4b756f5f5632a198de48a3930482a7d9c231360fa6348"
metafile = true

[[files]]
file = "options.txt"
hash = "c035308ea4033abce8815f5c6659d1c1fd6c9917b8671925f827052301fdb7d5"

[[files]]
file = "servers.dat"
hash = "aa165abb739f6a00d888b753d081dfe3c9d9fd90657ef71039486d5a0e77114d"
